# Generated by Django 4.1 on 2022-09-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trains", "__first__"),
        ("cities", "0002_alter_city_options_alter_city_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Name of  route"
                    ),
                ),
                (
                    "travel_times",
                    models.PositiveSmallIntegerField(verbose_name="Time in travel"),
                ),
                (
                    "from_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_from_city_set",
                        to="cities.city",
                        verbose_name="From city",
                    ),
                ),
                (
                    "to_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_to_city_set",
                        to="cities.city",
                        verbose_name="To city",
                    ),
                ),
                (
                    "trains",
                    models.ManyToManyField(
                        to="trains.train", verbose_name="Trains list"
                    ),
                ),
            ],
            options={
                "verbose_name": "Path",
                "verbose_name_plural": "Paths",
                "ordering": ["travel_times"],
            },
        ),
    ]
